### ISSUE TITLE
HTML Comments

### ISSUE THREAD

**Issue by jghauser** [ikatyang/tree-sitter-markdown#25]
I'm using tree-sitter-markdown with nvim-treesitter, and I'm not sure whether what I'm seeing is some artifact from the combination of these two programs or an issue with tree-sitter-markdown. But just in case it's an issue with the parser, here's something I've found.

I've noticed that when an html comment (`<!-- comment -->`) begins a line, it seems to be recognised correctly as a comment (and highlighted with a sort of greyed out color in neovim). However, when a comment is inline (`This is a sentence<!-- comment --> with a comment.`), then the comment shows up just like normal text. Finally, when the line starts with a comment and also contains inline comments (`<!-- comment -->This is a sentence<!-- comment --> with a comment.`), then all comments are displayed correctly again.

**Comment by ikatyang** [comment]
According to the CommonMark spec, the case 1 and case 3 are considered html block and the case 2 is considered a paragraph with inline html, I guess the highlight query you used only configured the query for [html block](https://github.com/ikatyang/tree-sitter-markdown/blob/5a139bed455268a06410471bf48b19d11abdd367/grammar.js#L225) but not for [inline html](https://github.com/ikatyang/tree-sitter-markdown/blob/5a139bed455268a06410471bf48b19d11abdd367/grammar.js#L251-L257).

**Comment by jghauser** [comment]
Thanks, I'm closing this as it's not an issue with tree-sitter-markdown. I'll open an issue at nvim-treesitter to ask how to get the highlighting right.
