### ISSUE TITLE
binding for rust

### ISSUE THREAD

**Issue by tami5** [ikatyang/tree-sitter-markdown#27]
Hey @ikatyang it would be great if there's a binding for rust. I tried to do it my self using tree-sitter guide but failed to do so many times. Here how tree-sitter-rust does it https://github.com/tree-sitter/tree-sitter-rust/tree/master/bindings/rust.

Thanks

**Comment by ikatyang** [comment]
👉 https://crates.io/crates/tree-sitter-markdown

**Comment by tami5** [comment]
:heart: can't wait to start experimenting and try to build something reusable. Thanks @ikatyang
