### ISSUE TITLE
soft_line_break contain ">" when parsing blockquote

### ISSUE THREAD

**Issue by coiby** [ikatyang/tree-sitter-markdown#8]
Currently, blockquote
```markdown
> 1
> 2
```

is parsed as

```yaml
document [0, 0] - [1, 3])
  block_quote [0, 0] - [1, 3])
    paragraph [0, 2] - [1, 3])
      text [0, 2] - [0, 3])
      soft_line_break [0, 3] - [1, 2])
      text [1, 2] - [1, 3])
```

which means soft_line_break is `\n>`. I think it's wrong to contain `>`.

**Comment by ikatyang** [comment]
Ref: https://spec.commonmark.org/0.29/#paragraph-continuation-text

It is technically a soft line break since the `>` there is ignorable, i.e.

```md
> 1
> 2
```

is same as

```md
> 1
2
```

Could you share the reason why you don't want to parse it as a soft line break?

**Comment by coiby** [comment]
It's my gut reaction. I'm using Qt's QTextEdit to render markdown files based on the syntax tree produced by tree-sitter-marrdown. I'll see how it works out and come back after a while.
